### ISSUE TITLE
The API appears to be down.

### ISSUE THREAD

**Issue by antoniovleonti** [ngocsangyem/freedictionaryapi#1]
Check https://api.freedictionary.dev/api/v1/entries/en/go

**Comment by ngocsangyem** [comment]
Hi @antoniovleonti, Because of the limited budget, I temporarily shut down the server. But you can fork this project and host it by yourself. Then add linguarobot API key to `.env` or you can use any modules in `src/modules`. Thank you

**Comment by antoniovleonti** [comment]
Thanks for the response!
